import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CENTRAL DE APRENSENTAÇÃO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CENTRAL DE APRESENTAÇÃO
        </h1>
        <Link href="/presentation">
              <a className={styles.card}>
              <h2>APRESENTAÇÃO PMI</h2>
              </a>
        </Link>
        
        </main>

      <footer className={styles.footer}>
        <p>Developed by Jota</p>
      </footer>
    </div>
  )
}
